repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
      - id: black
        language_version: python3.7
        exclude: ^tests/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
        exclude: ^tests/
    -   id: check-case-conflict
    -   id: check-symlinks
    -   id: check-added-large-files