language: python
os:
- linux
python:
- '3.6'
install:
- pip install -U twine
- pip install coveralls
- pip install pytest-pep8 coverage pytest-cov -U
- pip install -e .
script:
- py.test tests --cov solt --cov-report term-missing -v
after_success:
- coveralls
deploy:
  on:
    branch: master
  provider: pypi
  user: lext
  password:
    secure: BuC3Uf+aqgyOhCjhKIh/LwmdeaBle8DydFSIC3derHzLzsmtqIt1B4cLPbbJhfnm40pUlDWmIqoU+OvY0XlOWbixmNesxX5XA9AXDPLKMOCjMy4eQcDpB5irSeHvVpBjE082nYL9dfwMqpl0YcIhYoWdftSvITdlpPSVTjoFZ7ayp+WAT6faA3Hrd7AGGWWUiagFcoS0Sb87KQ42siXk8Y3kkhKDNoEs3MU3YPTqjx1kVrsfKqISEvKsz8/Ru8fKFyxEnW89aXw2dG18Lw/vuHiulWU0ZnoS/Udov9U+OaSFM0EcUBIUNfjTrnKqfP1asr7cj7Ih+0WNRUMXV2OiPeVfeIFh9KNineoVUlS/Olku0OFuObvtV6JjCcORfPPqTq4LZbtqqO68zb5ALYCMFzOPofn+u2Kh6oTO3c/hr3j1Sz1J+Uu9vPnHDHzsFE3yqXIrG1ZbjWbogB744Nc82T8lILLup1965/BLI6Sk2XGNFRHdo+KEYxgGmhyRvReYXOO3GJgbcGqIwTt7xMhn7JmHEOei1wM22X4RSwE6WnpUC9yAJByzXI2gbR+rjhz94WH2lbtILFZgOKJkj6ghgh3gdZcpWtZpd/HYuD7xoEGFCOjn9/bMvASzwSk+5R03QwUMqX6bwTlRSoG9ryAZFx91oUazOfAWgw4f/UXq5jY=
