language: python

matrix:
  include:
    - name: "Linux / Python 3.6"
      os: linux
      dist: xenial
      sudo: true
      python: 3.6

    - name: "Linux / Python 3.7"
      os: linux
      dist: xenial
      sudo: true
      python: 3.7

    - name: "OSX/ Python 3.6"
      os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6

    - name: "OSX / Python 3.7"
      os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7

install:
  - sh ci/conda_setup.sh
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda
  - export OPATH="$PATH" && export PATH="$HOME/miniconda/bin:$PATH"
  - conda create -q -y -n solt_test_env python=$TRAVIS_PYTHON_VERSION
  - conda install -y -n solt_test_env pandoc
  - source activate solt_test_env
  - pip install -r ci/requirements.txt
  - pip install .
script:
  - py.test tests --cov solt --cov-report term-missing -v
  - flake8
after_success:
  - codecov

deploy:
  - provider: pypi
    distributions: sdist
    user: lext
    password:
      secure: oyNWzjK7EzR9Q9k/hso7uDDTIqK67e/OhqGYtbd3g7x5TDSrhpettRy5Q5bmsWU+ZT+iLuSr1oRQ0DFPIsczc65INKQbLkmyWg6kTbDlD4OLSAjUTT31HiUERnkTVU4Q+pxiEli5zwkVrEGqwe8AN9ZFNE95OespM9967nk4RAON+97IyVOIujBm+4MFrmNQrmDc5cLhm/H2VXEd/BRa+04zujt5MX4EgdxIFfNZ6bRFf+vScT/kqR7SLxlfXsVq05dSd8cWDD4Qm6+Z8sguCuaZf+F19FVIhkNDvEONvP9CnC0M8KmtBgmjeaXavz+Bo9x+GmjMYVttOIzg3xlbofhMSAUnKm2YMUhtPkCWFIlWdZmyCLLGkSFo5KUhf/zBoScWap9ZG4GC+wEiEB7bCn/2lkT9BqmPlCNgTFSgnB7+jCYRZ+l/Lr0fSYHqXXJXDEOxAcMAHOM5I/XJDIT0vndlVCpwavM/OrSZAEL7cozYqKqUutEr6izJbZ3usSEHisdG8m9fjoC7S46gAotFqt1o7w4QUyGHhGXtQQZTCLg3ctdvSQw187CruTP9T5Wj7Hfx95S9JKyMIGr5BGb+4+SjB4IsiboPygCKMpD3AL/gzmKP/ZXvGkDbz7puj/5jINFyo4Odd2gO9mHR//+B9Su1ArZWHSW+zlrDnYsi6DU=
    on:
      tags: true
    skip_existing: true
  - provider: script
    script: sh ci/doc_build.sh
    on:
      branch: master